# Numpy Quick Review

##  Numpy

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy as sp
import seaborn as sns
plt.style.use('seaborn')
%matplotlib inline

In [9]:
L = [1,2,3]

In [10]:
A = np.array([1,2,3])

In [11]:
for e in L:
    print(e)

1
2
3


In [12]:
A + A

array([2, 4, 6])

In [15]:
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [16]:
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])

In [17]:
np.exp(A)

array([  2.71828183,   7.3890561 ,  20.08553692])

![adotb](adotb.png)
![adotbcos](adotbcos.png)
![cos](cos.png)

In [19]:
a = np.array([1,2])
b = np.array([2,1])

In [20]:
dot = 0

In [21]:
for e,f in zip(a,b):
    dot += e * f

In [22]:
dot

4

In [23]:
a * b

array([2, 2])

In [24]:
np.sum(a*b)

4

In [25]:
(a*b).sum()

4

In [26]:
np.dot(a,b)

4

In [27]:
a.dot(b)

4

In [29]:
amag = np.sqrt((a * a).sum())
amag

2.2360679774997898

In [32]:
amag = np.linalg.norm(a)
amag

2.2360679774997898

# Dot product

In [33]:
from datetime import datetime

In [34]:
a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

In [43]:
def slow_dot_product(a, b):
    result = 0
    for e, f in zip(a, b):
        result += e * f
    return result

In [44]:
t0 = datetime.now()
for t in range(T):
    slow_dot_product(a,b)
dt1 = datetime.now() - t0

In [45]:
t0 = datetime.now()
for t in range(T):
    a.dot(b)
dt2 = datetime.now() - t0

In [46]:
print("dt1 / dt2 :", dt1.total_seconds()/dt2.total_seconds())

dt1 / dt2 : 30.839374468487197


#### Matrix

In [52]:
M = np.array([[1,2], [3,4]])
M

array([[1, 2],
       [3, 4]])

In [48]:
L = [[1,2], [3,4]]

In [49]:
L[0]

[1, 2]

In [50]:
M2 = np.matrix([[1,2], [3,4]])

In [51]:
M2

matrix([[1, 2],
        [3, 4]])

In [53]:
A = np.array(M2)

In [54]:
A.T

array([[1, 3],
       [2, 4]])

#### Generating matrices to work with

In [55]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [57]:
Z = np.zeros((10,10))
Z

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [59]:
O = np.ones((10,10))
O

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [61]:
R = np.random.random((10,10))
R

array([[ 0.25384365,  0.57845696,  0.56427604,  0.11899135,  0.95689393,
         0.90463666,  0.07756006,  0.35646304,  0.18195445,  0.73743895],
       [ 0.88038032,  0.19897849,  0.31218153,  0.94259714,  0.38437445,
         0.91114431,  0.99169475,  0.98948799,  0.10967955,  0.27039416],
       [ 0.5598967 ,  0.54879961,  0.88114709,  0.25241415,  0.70321149,
         0.58098399,  0.44147973,  0.3026874 ,  0.99673188,  0.76598508],
       [ 0.42551915,  0.77766014,  0.58736501,  0.4489661 ,  0.08499893,
         0.5990156 ,  0.69017502,  0.67400171,  0.24333183,  0.14971279],
       [ 0.53737809,  0.20499385,  0.02231174,  0.86962365,  0.02759487,
         0.13144331,  0.22968958,  0.38161216,  0.71769555,  0.05287119],
       [ 0.01089372,  0.58886398,  0.95791182,  0.41560697,  0.97668137,
         0.64107419,  0.60576256,  0.68811928,  0.79812811,  0.22672867],
       [ 0.61663282,  0.50307648,  0.65088701,  0.75737456,  0.6165513 ,
         0.71952756,  0.19086578,  0.0386038 

In [62]:
G = np.random.randn(10,10)

In [63]:
G

array([[-1.0786881 ,  1.55318513, -0.2556223 , -0.11787361,  0.56715688,
         2.03912393, -1.11537805, -0.70092809,  0.79059104,  1.11938181],
       [-0.83247691,  1.12575688, -1.67279424, -0.51570246,  0.56053341,
         0.25453129,  0.62930663, -1.67120602, -0.31185744,  0.82946899],
       [ 1.34717907, -1.42760106,  0.07557797,  0.50021449,  0.26727434,
         1.76692735,  0.1878497 ,  0.42278848,  0.03250755,  0.14349773],
       [-1.52871223, -2.0903246 , -0.7214833 ,  0.30589442,  0.96181024,
         0.57802687,  1.24065341,  1.03242788,  0.87451639,  0.58788484],
       [-0.96383868,  0.23725876, -0.51201517,  1.59215486, -1.19855464,
        -0.82886758, -0.08252538, -0.46367903, -0.77067242, -1.91498951],
       [-1.48161935,  1.5279989 , -0.24736487, -0.33225143,  2.09243516,
        -1.38407313,  1.6563689 ,  2.0685401 , -0.95052444, -2.5978629 ],
       [-0.91716445, -0.91589802, -0.32715314, -0.37177454, -0.51820792,
         0.90958564,  0.43207312,  0.29810388

In [64]:
G.mean()

0.058899222692137189

In [65]:
G.var()

1.1188647322612284

#### Matrix Product

In [66]:
A = np.array([[1,2], [3,4]])

In [67]:
A_inv = np.linalg.inv(A)

In [71]:
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [73]:
A.dot(A_inv)

array([[  1.00000000e+00,   1.11022302e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [74]:
np.linalg.det(A)

-2.0000000000000004

In [75]:
np.diag(A)

array([1, 4])

In [76]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [77]:
a = np.array([1,2])
b = np.array([3,4])

In [78]:
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [79]:
np.inner(a,b)

11

In [85]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.outer(a,b)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [86]:
np.inner(a,b)

32

In [88]:
np.diag(A).sum()

5

In [89]:
np.trace(A)

5

In [90]:
X = np.random.randn(100,3)

In [91]:
cov = np.cov(X)
cov.shape

(100, 100)

In [92]:
cov = np.cov(X.T)

In [93]:
cov

array([[ 1.12464362, -0.00407458,  0.05858327],
       [-0.00407458,  1.0201339 , -0.12218936],
       [ 0.05858327, -0.12218936,  1.2889264 ]])

#### Eigenvalues and Eigenvectors
```
eigenvalues, eigenvectors = np.eig(C)

OR

eigenvalues, eigenvectors = np.eigh(C)

eigh is for symmetric and Hermitian matrices

Symmetric means A = A.T

Hermitian means A = A.H

A.H = conjugate transpose of A
```

In [94]:
np.linalg.eigh(cov)

(array([ 0.97082418,  1.11270172,  1.35017802]),
 array([[-0.11846174,  0.96296216, -0.24222035],
        [ 0.91942975,  0.1984984 ,  0.33948097],
        [ 0.37498768, -0.18248908, -0.90889052]]))

In [95]:
np.linalg.eig(cov)

(array([ 1.35017802,  1.11270172,  0.97082418]),
 array([[ 0.24222035, -0.96296216, -0.11846174],
        [-0.33948097, -0.1984984 ,  0.91942975],
        [ 0.90889052,  0.18248908,  0.37498768]]))

#### Sloving a Linear System

In [96]:
A

array([[1, 2],
       [3, 4]])

In [100]:
b = np.array([1,2])
b

array([1, 2])

In [103]:
w = np.linalg.inv(A).dot(b)
w

array([  2.22044605e-16,   5.00000000e-01])

In [105]:
w = np.linalg.solve(A, b)
w

array([ 0. ,  0.5])

#### Word Problem

In [108]:
A = np.array([[1,1], [1.5, 4]])
b = np.array([2200, 5050])
w = np.linalg.solve(A,b)
w

array([ 1500.,   700.])