# Numpy, Pandas, Matplotli, Scipy Quick Review

## 1. Numpy

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy as sp
import seaborn as sns
plt.style.use('seaborn')
%matplotlib inline

In [9]:
L = [1,2,3]

In [10]:
A = np.array([1,2,3])

In [11]:
for e in L:
    print(e)

1
2
3


In [12]:
A + A

array([2, 4, 6])

In [15]:
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [16]:
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])

In [17]:
np.exp(A)

array([  2.71828183,   7.3890561 ,  20.08553692])

![adotb](adotb.png)
![adotbcos](adotbcos.png)
![cos](cos.png)

In [19]:
a = np.array([1,2])
b = np.array([2,1])

In [20]:
dot = 0

In [21]:
for e,f in zip(a,b):
    dot += e * f

In [22]:
dot

4

In [23]:
a * b

array([2, 2])

In [24]:
np.sum(a*b)

4

In [25]:
(a*b).sum()

4

In [26]:
np.dot(a,b)

4

In [27]:
a.dot(b)

4

In [29]:
amag = np.sqrt((a * a).sum())
amag

2.2360679774997898

In [32]:
amag = np.linalg.norm(a)
amag

2.2360679774997898

# Dot product

In [33]:
from datetime import datetime

In [34]:
a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

In [43]:
def slow_dot_product(a, b):
    result = 0
    for e, f in zip(a, b):
        result += e * f
    return result

In [44]:
t0 = datetime.now()
for t in range(T):
    slow_dot_product(a,b)
dt1 = datetime.now() - t0

In [45]:
t0 = datetime.now()
for t in range(T):
    a.dot(b)
dt2 = datetime.now() - t0

In [46]:
print("dt1 / dt2 :", dt1.total_seconds()/dt2.total_seconds())

dt1 / dt2 : 30.839374468487197


#### Matrix

In [52]:
M = np.array([[1,2], [3,4]])
M

array([[1, 2],
       [3, 4]])

In [48]:
L = [[1,2], [3,4]]

In [49]:
L[0]

[1, 2]

In [50]:
M2 = np.matrix([[1,2], [3,4]])

In [51]:
M2

matrix([[1, 2],
        [3, 4]])

In [53]:
A = np.array(M2)

In [54]:
A.T

array([[1, 3],
       [2, 4]])

#### Generating matrices to work with

In [55]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [56]:
np.zeros((10,10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])