In [29]:
import numpy as np
x = np.array([1,3,4,5])
print(x, type(x))

y = np.arange(1, 10)
print(y, type(y), end="\n")

z = np.arange(1, 11, 2)
print(z, type(z))

# create one dimension zero matrix
a = np.zeros(3)
print(a, type(a[0]), end="\n\n")

""""
create n dimensions zero matrix

(first argument: row number
second argument: column number)

Second Argument: define element type
"""
b = np.zeros((3, 5), int)
print(b)

"""
Create one matrix
"""
c = np.ones((4,5))
print(c)


"""
Linear Space
"""
d = np.linspace(0, 10, 2)
print(d, type(d))

[1 3 4 5] <class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[1 3 5 7 9] <class 'numpy.ndarray'>
[ 0.  0.  0.] <class 'numpy.float64'>

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[  0.  10.] <class 'numpy.ndarray'>


In [44]:
"""
Linear Space
"""
d = np.linspace(0, 10, 6)
print(d, type(d), end="\n\n")

e = np.linspace(0, 10, 51)
print(e, type(e))

[  0.   2.   4.   6.   8.  10.] <class 'numpy.ndarray'>

[  0.    0.2   0.4   0.6   0.8   1.    1.2   1.4   1.6   1.8   2.    2.2
   2.4   2.6   2.8   3.    3.2   3.4   3.6   3.8   4.    4.2   4.4   4.6
   4.8   5.    5.2   5.4   5.6   5.8   6.    6.2   6.4   6.6   6.8   7.
   7.2   7.4   7.6   7.8   8.    8.2   8.4   8.6   8.8   9.    9.2   9.4
   9.6   9.8  10. ] <class 'numpy.ndarray'>


In [50]:
# Create Square Matrix- Identity Matrix
f = np.eye(5)
f

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [55]:
# CAREATE RANDOM SERIES

# [0, 1], uniform distribution to selection
g = np.random.rand(1)
print(g, type(g))

h = np.random.rand(5, 5)
print(h, type(h))


# Standard normal distribution
i = np.random.randn(5)
print(i, end="\n\n")

j = np.random.randn(5, 5)
print(j)

[ 0.9286663] <class 'numpy.ndarray'>
[[ 0.83896908  0.31970087  0.7374929   0.58846903  0.83707323]
 [ 0.36780324  0.05535425  0.34725955  0.59998186  0.45525366]
 [ 0.2791091   0.11437377  0.94101157  0.10670065  0.48036063]
 [ 0.30325359  0.46651765  0.78433194  0.73289278  0.62000843]
 [ 0.95148827  0.59706643  0.3964598   0.44799558  0.10585323]] <class 'numpy.ndarray'>
[ 1.15571794  0.46297031 -0.61455675 -1.57259562  0.35582543]

[[-1.27729057  0.46629182 -1.3509194   1.70757507  0.57708072]
 [ 0.07746833  0.83894576  0.68873918 -0.66993867  0.32722663]
 [ 0.86269146  0.56643536 -0.80837036  0.77224961  1.24534125]
 [-0.62800048  0.14199658  0.31847964 -1.74032759 -0.00430794]
 [ 1.12192024 -1.86072947  0.51033885 -0.71746488  0.14743695]]


In [61]:
# random integer
# randint(lower, higher)
aa = np.random.randint(1, 200)
print(aa)

#Spicify a list
bb = np.random.randint(1, 100, 10)
print("\n", bb)

91

 [38  8 47 57 63 10 76  4  8  9]


In [75]:
# Array Comparation
arr = np.arange(24)
ranarr = np.random.randint(0, 50, 10)

print(arr)
print("\n", ranarr)

arr = arr.reshape(4,6)
print("\n", arr)

# shape
print(ranarr.shape)
print(arr.shape)

# Reshape
arr = arr.reshape(24, 1)
print("\n", arr.reshape(24, 1))
print(arr.shape)

# grab data type
print(arr.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

 [ 7 27 19 25 17 38 10 27 39  2]

 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(10,)
(4, 6)

 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
(24, 1)
int64


In [78]:
# get max, min
print(arr.max())
print(ranarr.min())
print(ranarr.mean())

23
2
21.1


In [80]:
# get the index of minimum value and maximum value
print(ranarr.argmax())
print(ranarr.argmin())

8
9


In [109]:
a = np.arange(10)

# Additioin, substraction, times, division
b = a + a
print("Addition: ", b, type(b))

print("Substration: ",a - a)
print("Multiplication: ", a * a)
print("Division: ",a[1:]/a[1:])
print("1/array: ", 1/a)
print("+ 100: ", a + 100)
print("power of 2", a ** 2)

Addition:  [ 0  2  4  6  8 10 12 14 16 18] <class 'numpy.ndarray'>
Substration:  [0 0 0 0 0 0 0 0 0 0]
Multiplication:  [ 0  1  4  9 16 25 36 49 64 81]
Division:  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
1/array:  [        inf  1.          0.5         0.33333333  0.25        0.2
  0.16666667  0.14285714  0.125       0.11111111]
+ 100:  [100 101 102 103 104 105 106 107 108 109]
power of 2 [ 0  1  4  9 16 25 36 49 64 81]


/Users/liyixuan1121/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in true_divide
  # Remove the CWD from sys.path while we load stuff.


In [108]:
# List operation
a = [1]
print("Mulitplication: ", a * 4)
print("Times 0: ", a * 0)
print("Mulitiplication: ", [[1] * 4] * 4)

Mulitplication:  [1, 1, 1, 1]
Times 0:  []
Mulitiplication:  [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]


In [112]:
# Numpy Math Operation
print(np.exp(a))
print(np.max(a))
print(np.sqrt(a))
print(np.log(a[1:]))

[  1.00000000e+00   2.71828183e+00   7.38905610e+00   2.00855369e+01
   5.45981500e+01   1.48413159e+02   4.03428793e+02   1.09663316e+03
   2.98095799e+03   8.10308393e+03]
9
[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131  2.82842712  3.        ]
[ 0.          0.69314718  1.09861229  1.38629436  1.60943791  1.79175947
  1.94591015  2.07944154  2.19722458]
