In [29]:
import numpy as np
x = np.array([1,3,4,5])
print(x, type(x))

y = np.arange(1, 10)
print(y, type(y), end="\n")

z = np.arange(1, 11, 2)
print(z, type(z))

# create one dimension zero matrix
a = np.zeros(3)
print(a, type(a[0]), end="\n\n")

""""
create n dimensions zero matrix

(first argument: row number
second argument: column number)

Second Argument: define element type
"""
b = np.zeros((3, 5), int)
print(b)

"""
Create one matrix
"""
c = np.ones((4,5))
print(c)


"""
Linear Space
"""
d = np.linspace(0, 10, 2)
print(d, type(d))

[1 3 4 5] <class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[1 3 5 7 9] <class 'numpy.ndarray'>
[ 0.  0.  0.] <class 'numpy.float64'>

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[  0.  10.] <class 'numpy.ndarray'>


In [44]:
"""
Linear Space
"""
d = np.linspace(0, 10, 6)
print(d, type(d), end="\n\n")

e = np.linspace(0, 10, 51)
print(e, type(e))

[  0.   2.   4.   6.   8.  10.] <class 'numpy.ndarray'>

[  0.    0.2   0.4   0.6   0.8   1.    1.2   1.4   1.6   1.8   2.    2.2
   2.4   2.6   2.8   3.    3.2   3.4   3.6   3.8   4.    4.2   4.4   4.6
   4.8   5.    5.2   5.4   5.6   5.8   6.    6.2   6.4   6.6   6.8   7.
   7.2   7.4   7.6   7.8   8.    8.2   8.4   8.6   8.8   9.    9.2   9.4
   9.6   9.8  10. ] <class 'numpy.ndarray'>
